### ISSUE TITLE
Feros Geth Armature Revives Itself

### ISSUE THREAD

**Issue by ShredzAlot** [henbagle/LE1CommunityPatch#171] opened 2022-10-19 22:16 UTC
**Describe the bug**
Geth Armature basically comes back to life if you kill it then loot the container right after. Video provided.

**Location**
In that one room as you enter the Exogeni building. Before you jump down the hole where you encounter Lizbeth.

**Screenshots & Saves**

https://user-images.githubusercontent.com/95461294/196814513-b83afbe7-3a09-404a-b9f9-38787ea1ba26.mp4

**Comment by vegz** [comment] 2022-10-26 16:40
File: BIOA_WAR50_02_DSG 

The issue seems to be caused by the interpdata for reviving the armature activates after that crate is used, the level is loaded and if you shoot at it. It would probably be easiest to fix by adding a bool and transition to check for if its already been activated.

![Armtetur](https://user-images.githubusercontent.com/40906382/198084600-d934fbb6-39df-4a46-a045-409ca5cba1a1.png)

**Comment by henbagle** [comment] 2022-10-31 20:27
Fixed. Self-closing gate added to the ArtPlaceableUsed and TakeDamage options so that only one of them can be triggered. The LevelLoaded is still directly connected to the Interp, as this triggers the start of an animation that is then paused to preset the state of the armature.

![image](https://user-images.githubusercontent.com/8151477/199103854-947c7594-f304-4973-9f8c-463dbbf0c65c.png)

**Closed** 2023-02-24 21:15 UTC
Labels: fixed, bug
